# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Hugo Now"
license = "MIT"
licenselink = "https://github.com/mikeblum/hugo-now/blob/master/LICENSE.md"
description = "a Hugo port of Jekyll Now"
homepage = "https://github.com/mikeblum/hugo-now"
tags = ["blog", "profile", "jekyll-now", "bootstrap", "font awesome", "responsive", "pygments"]
features = ["blog", "portfolio"]
min_version = 0.24

[author]
  name = "Michael Blum"
  homepage = "https://mblum.me"

# If porting an existing theme
[original]
  name = "Jekyll Now"
  homepage = "http://www.jekyllnow.com/"
  repo = "https://github.com/barryclark/jekyll-now"